# Folder and file naming standard
#
# kebab-case - file and direectories (ie.: components/auto-box/auto-box.tsx)
# kebab-case - used for any other folder and file
# PascalCase - should be avoided
# camelCase - should be avoided

ls:
  # global file rules
  # .js and sub-extensions
  .js: kebab-case
  .config.js: lowercase
  # .ts and sub-extensions
  .ts: kebab-case
  .test.ts: kebab-case
  .mock.ts: kebab-case
  .types.ts: kebab-case
  .utils.ts: kebab-case
  .mapping.ts: kebab-case
  .definition.ts: kebab-case
  .constants.ts: kebab-case
  .d.ts: kebab-case
  # .tsx and sub-extensions
  .tsx: kebab-case
  .stories.tsx: kebab-case
  .styles.ts: kebab-case
  .template.ts: kebab-case

  # directory rules
  ./**/{__tests__,__mocks__}:
    .dir: lowercase

ignore:
  - .git
  - node_modules
  - dist
  - .storybook
  - storybook-static
  - babel.config.js
  - sst.config.ts
  # package specific - directory patterns not yet implemented for ignore: https://ls-lint.org/1.x/configuration/the-basics.html#using-directory-patterns
  - apps
  - library/foundations/node_modules
  - library/core-components/node_modules
  - library/foundations/dist
  - library/core-components/dist
