name: deploy demo app for PR preview

on:
  pull_request:
    branches: ['main']

jobs:
  main:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout the codebase
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.cache
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Validate tokens
        id: validate-tokens
        working-directory: library/foundations
        run: |
          # Parse and Validate Design Tokens
          yarn tokens:ci

      - name: Lint
        run: yarn lint:ci

      - name: Build Demo App
        run: npx nx run demo:build

      - name: Configure AWS credentials for deployment
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      ## Deploy remix demo app with SST
      - name: Deploy Demo App to AWS
        run: yarn sst deploy --stage radius-pr

      # Find existing Demo App comment
      - name: Find Existing Comment
        uses: peter-evans/find-comment@v2
        id: fc
        with:
          issue-number: ${{ github.event.pull_request.number }}
          comment-author: 'github-actions[bot]'
          body-includes: Demo App Preview

      # Create new comment with Demo App URL, if one does not exist already
      - name: Comment on PR with link to deployed demo app
        if: steps.fc.outputs.comment-id == ''
        uses: peter-evans/create-or-update-comment@v2
        with:
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            Demo App Preview: https://d11mwnosflssyy.cloudfront.net/
